# Generated by Django 4.2.25 on 2025-10-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_maps_url",
                    models.URLField(
                        help_text="Original Google Maps URL used to generate this route.",
                        max_length=500,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="Human-readable starting location of the route.",
                        max_length=200,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Human-readable ending location of the route.",
                        max_length=200,
                    ),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total distance of the route in kilometers.",
                        max_digits=7,
                    ),
                ),
                (
                    "waypoints",
                    models.JSONField(
                        default=list,
                        help_text="List of waypoint dictionaries with lat, lng, country_code, and distance_from_start.",
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        default=list,
                        help_text="List of ISO country codes encountered along the route.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the route was created.",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
