# Generated by Django 4.2.25 on 2025-10-22 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="user",
            field=models.ForeignKey(
                help_text="User who created this route.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["-created_at"], name="routes_rout_created_6f595f_idx"
            ),
        ),
    ]
