# Generated by Django 4.2.25 on 2025-10-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="countries",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ISO country codes encountered along the route.",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="waypoints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of waypoint dictionaries with lat, lng, country_code, and distance_from_start.",
            ),
        ),
    ]
