# Generated by Django 4.2.25 on 2025-11-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_alter_route_countries_alter_route_waypoints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="google_maps_url",
        ),
    ]
