# Generated by Django 4.2.26 on 2026-03-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='segments',
            field=models.JSONField(default=list, help_text='Route aggregated into continuous country blocks from border to border.'),
        ),
    ]
