# Generated by Django 4.2.25 on 2025-10-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable vehicle name, unique per user.",
                        max_length=100,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("gasoline", "Gasoline"), ("diesel", "Diesel")],
                        db_index=True,
                        help_text="Fuel variant consumed by this vehicle.",
                        max_length=10,
                    ),
                ),
                (
                    "avg_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average fuel consumption in L/100km.",
                        max_digits=4,
                    ),
                ),
                (
                    "tank_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total tank capacity in liters.",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
