# Generated by Django 4.2.25 on 2025-10-22 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                help_text="Owner of the vehicle.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["user", "fuel_type"], name="cars_car_user_id_a3a43e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={("user", "name")},
        ),
    ]
