# Generated by Django 4.2.25 on 2025-10-22 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g. PL, DE).",
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_country_code",
                                message="Country code must be exactly 2 uppercase letters (ISO 3166-1 alpha-2 format).",
                                regex="^[A-Z]{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable country name.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("gasoline", "Gasoline"), ("diesel", "Diesel")],
                        db_index=True,
                        help_text="Fuel variant this price entry refers to.",
                        max_length=10,
                    ),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Fuel price per liter expressed in the specified currency.",
                        max_digits=5,
                    ),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp when the price was scraped from external source.",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country for which this price applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_prices",
                        to="fuel_prices.country",
                    ),
                ),
            ],
            options={
                "ordering": ("country__name", "fuel_type"),
                "unique_together": {("country", "fuel_type")},
            },
        ),
    ]
