# Generated by Django 4.2.25 on 2025-10-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                help_text="ISO 3166-1 alpha-2 country code (e.g. PL, DE).",
                max_length=2,
                unique=True,
            ),
        ),
    ]
