# Generated by Django 4.2.25 on 2025-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_prices", "0002_alter_country_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fuelprice",
            options={"ordering": ("-scraped_at", "country__name", "fuel_type")},
        ),
        migrations.AlterUniqueTogether(
            name="fuelprice",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="fuelprice",
            index=models.Index(
                fields=["country", "fuel_type", "-scraped_at"],
                name="fuel_prices_country_b85fd7_idx",
            ),
        ),
    ]
