# Generated by Django 4.2.25 on 2025-10-29 15:11

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_prices", "0003_alter_fuelprice_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fuelprice",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("scraped_at"),
                models.F("country"),
                models.F("fuel_type"),
                name="unique_fuel_price_per_day",
                violation_error_message="Only one price per country, fuel type, and day is allowed.",
            ),
        ),
    ]
