# Generated by Django 4.2.25 on 2025-10-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("fuel_prices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefuelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservoir_km",
                    models.IntegerField(
                        default=100,
                        help_text="Safety reserve distance in kilometers to maintain in tank.",
                    ),
                ),
                (
                    "optimization_strategy",
                    models.CharField(
                        choices=[
                            ("cheapest", "Cheapest price"),
                            ("min_stops", "Minimum stops"),
                            ("balanced", "Balanced approach"),
                        ],
                        help_text="Optimization approach used to compute this plan.",
                        max_length=20,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total fuel cost for the entire route in EUR.",
                        max_digits=8,
                    ),
                ),
                (
                    "total_fuel_needed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total liters of fuel required for the route.",
                        max_digits=7,
                    ),
                ),
                (
                    "number_of_stops",
                    models.IntegerField(
                        help_text="Number of refueling stops in this plan."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the plan was generated.",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        help_text="Vehicle configuration used in this plan.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refuel_plans",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RefuelStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_number",
                    models.IntegerField(
                        help_text="Sequential stop number (1, 2, 3, etc.)."
                    ),
                ),
                (
                    "distance_from_start_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance from route origin to this stop in kilometers.",
                        max_digits=7,
                    ),
                ),
                (
                    "fuel_to_add_liters",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Liters of fuel to add at this stop.",
                        max_digits=5,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of fuel purchased at this stop in EUR.",
                        max_digits=7,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate of the stop location.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate of the stop location.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country where this refueling occurs.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refuel_stops",
                        to="fuel_prices.country",
                    ),
                ),
                (
                    "fuel_price",
                    models.ForeignKey(
                        help_text="Fuel price entry used for this stop.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refuel_stops",
                        to="fuel_prices.fuelprice",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Parent refuel plan containing this stop.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="planner.refuelplan",
                    ),
                ),
            ],
            options={
                "ordering": ("stop_number",),
            },
        ),
    ]
