# Generated by Django 4.2.25 on 2025-10-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planner", "0001_initial"),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refuelplan",
            name="route",
            field=models.ForeignKey(
                help_text="Route for which this plan was generated.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refuel_plans",
                to="routes.route",
            ),
        ),
        migrations.AddIndex(
            model_name="refuelstop",
            index=models.Index(
                fields=["plan", "country"], name="planner_ref_plan_id_0d638d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="refuelstop",
            unique_together={("plan", "stop_number")},
        ),
        migrations.AddIndex(
            model_name="refuelplan",
            index=models.Index(
                fields=["-created_at"], name="planner_ref_created_220ec4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refuelplan",
            index=models.Index(
                fields=["route", "car", "optimization_strategy"],
                name="planner_ref_route_i_2b2d69_idx",
            ),
        ),
    ]
